// TEST ONLY. Every key this script writes is a throwaway test key with no
// production meaning. Never reuse any of it anywhere.
//
// Generates the Case A fixture set: a root principal, a parent agent, a child
// agent, a valid root->parent->child chain, and the variant chains and
// revocation states the P1 and P2 cases need.

import { mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  generateKeyPair,
  signAuthorityDelegation,
  computeAuthorityDelegationId,
  verifyAuthorityDelegationChain,
} from 'agent-passport-system'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT = HERE

const TEST_ONLY_HEADER =
  'TEST ONLY: throwaway deterministic test material. Not a production key, ' +
  'identity, or authority. Generated by fixtures/generate.mjs.'

// Deterministic identities. Keys are generated once and committed, so every run
// of the suite verifies the same bytes.
const ROOT = 'aps:agent:test-root-principal'
const PARENT = 'aps:agent:test-parent-agent'
const CHILD = 'aps:agent:test-child-agent'

const SANDBOX_ID = 'sbx-aps-case-a-child'

// A fixed clock. `now` used by the middleware at evaluation time is supplied by
// the runner so the same signed records serve the valid and expired cases.
const T = {
  rootIssued: '2026-01-01T00:00:00.000Z',
  rootNotBefore: '2026-01-01T00:00:00.000Z',
  rootNotAfter: '2027-01-01T00:00:00.000Z',
  childIssued: '2026-02-01T00:00:00.000Z',
  childNotBefore: '2026-02-01T00:00:00.000Z',
  childNotAfter: '2026-12-01T00:00:00.000Z',
  // An already-expired child window, still inside the parent's window.
  childExpiredNotBefore: '2026-02-01T00:00:00.000Z',
  childExpiredNotAfter: '2026-03-01T00:00:00.000Z',
}

// Deterministic nonces so the committed fixture bytes are stable.
const NONCE = {
  root: '00000000000000000000000000000001',
  child: '00000000000000000000000000000002',
  childWide: '00000000000000000000000000000003',
  childExpired: '00000000000000000000000000000004',
}

function authority({ grants, notBefore, notAfter, depth, ceiling, reversibility }) {
  return {
    scope: { profile: 'aps-hierarchical-v1', grants },
    spend: { mode: 'bounded', unit: 'iso4217:USD:minor', per_action: '1000', cumulative: '100000' },
    depth: { remaining: depth },
    time: { not_before: notBefore, not_after: notAfter },
    reputation: { profile: 'aps-score-0-100-v1', ceiling },
    values: { profile: 'aps-values-identifiers-v1', required: [] },
    reversibility: { profile: 'aps-tci-v1', ceiling: reversibility },
  }
}

function issue({ parentId, issuer, subject, verificationMethod, issuedAt, nonce, auth, privateKey }) {
  const body = {
    record_type: 'aps:authority-delegation:v1',
    version: '1.0',
    parent_delegation_id: parentId,
    issuer,
    subject,
    verification_method: verificationMethod,
    issued_at: issuedAt,
    nonce,
    authority: auth,
  }
  const delegation_id = computeAuthorityDelegationId(body)
  const unsigned = { ...body, delegation_id }
  const signature = signAuthorityDelegation(unsigned, privateKey)
  return { ...unsigned, signature }
}

const rootKeys = generateKeyPair()
const parentKeys = generateKeyPair()
const childKeys = generateKeyPair()

const ROOT_VM = `${ROOT}#key-1`
const PARENT_VM = `${PARENT}#key-1`

// chain[0]: the root principal's grant to the parent agent. This is the
// ancestor the RED case revokes.
const rootToParent = issue({
  parentId: null,
  issuer: ROOT,
  subject: PARENT,
  verificationMethod: ROOT_VM,
  issuedAt: T.rootIssued,
  nonce: NONCE.root,
  auth: authority({
    grants: ['net:http:*'],
    notBefore: T.rootNotBefore,
    notAfter: T.rootNotAfter,
    depth: 4,
    ceiling: 90,
    reversibility: 'compensable',
  }),
  privateKey: rootKeys.privateKey,
})

// chain[1]: the parent agent's narrowed grant to the child agent.
const parentToChild = issue({
  parentId: rootToParent.delegation_id,
  issuer: PARENT,
  subject: CHILD,
  verificationMethod: PARENT_VM,
  issuedAt: T.childIssued,
  nonce: NONCE.child,
  auth: authority({
    grants: ['net:http:get'],
    notBefore: T.childNotBefore,
    notAfter: T.childNotAfter,
    depth: 2,
    ceiling: 70,
    reversibility: 'tentative',
  }),
  privateKey: parentKeys.privateKey,
})

// P2 case 1: a child that requests authority OUTSIDE the signed parent
// authority. Scope widened from net:http:get to net:*, which no narrowing of
// the parent's net:http:* covers.
const parentToChildWidened = issue({
  parentId: rootToParent.delegation_id,
  issuer: PARENT,
  subject: CHILD,
  verificationMethod: PARENT_VM,
  issuedAt: T.childIssued,
  nonce: NONCE.childWide,
  auth: authority({
    grants: ['net:*'],
    notBefore: T.childNotBefore,
    notAfter: T.childNotAfter,
    depth: 2,
    ceiling: 70,
    reversibility: 'tentative',
  }),
  privateKey: parentKeys.privateKey,
})

// P2 case 3: an expired link. The child's window closed 2026-03-01.
const parentToChildExpired = issue({
  parentId: rootToParent.delegation_id,
  issuer: PARENT,
  subject: CHILD,
  verificationMethod: PARENT_VM,
  issuedAt: T.childIssued,
  nonce: NONCE.childExpired,
  auth: authority({
    grants: ['net:http:get'],
    notBefore: T.childExpiredNotBefore,
    notAfter: T.childExpiredNotAfter,
    depth: 2,
    ceiling: 70,
    reversibility: 'tentative',
  }),
  privateKey: parentKeys.privateKey,
})

// P2 case 4a: tampered chain, one byte changed in a signed field. The last hex
// character of the child's nonce is altered, which changes the signed body
// without changing its shape.
const tamperedNonce = NONCE.child.slice(0, -1) + (NONCE.child.endsWith('2') ? '3' : '2')
const parentToChildTampered = { ...parentToChild, nonce: tamperedNonce }

// P2 case 4b: wrong signature. The child's record is re-signed with the child's
// own key rather than the parent's, so the signature is well formed but is not
// the issuer's.
const parentToChildWrongSigner = (() => {
  const { signature: _drop, ...unsigned } = parentToChild
  return { ...unsigned, signature: signAuthorityDelegation(unsigned, childKeys.privateKey) }
})()

function write(name, value) {
  writeFileSync(join(OUT, name), JSON.stringify(value, null, 2) + '\n')
}

rmSync(join(OUT, 'chains'), { recursive: true, force: true })
mkdirSync(join(OUT, 'chains'), { recursive: true })
rmSync(join(OUT, 'revocations'), { recursive: true, force: true })
mkdirSync(join(OUT, 'revocations'), { recursive: true })

write('keys.TEST-ONLY.json', {
  _comment: TEST_ONLY_HEADER,
  root: { agent_id: ROOT, verification_method: ROOT_VM, ...rootKeys },
  parent: { agent_id: PARENT, verification_method: PARENT_VM, ...parentKeys },
  child: { agent_id: CHILD, ...childKeys },
})

write('trust-anchors.TEST-ONLY.json', {
  _comment: TEST_ONLY_HEADER,
  // Accepted chain roots, by the root record's issuer and subject.
  roots: [{ issuer: ROOT, subject: PARENT }],
  // Verification keys by verification_method. Public keys only.
  keys: {
    [ROOT_VM]: rootKeys.publicKey,
    [PARENT_VM]: parentKeys.publicKey,
  },
})

write('mapping.TEST-ONLY.json', {
  _comment: TEST_ONLY_HEADER + ' Operator-owned sandbox_id -> APS agent_id map. Not a cryptographic binding.',
  sandboxes: { [SANDBOX_ID]: CHILD },
})

const CHAINS = {
  valid: [rootToParent, parentToChild],
  widened: [rootToParent, parentToChildWidened],
  expired: [rootToParent, parentToChildExpired],
  tampered: [rootToParent, parentToChildTampered],
  'wrong-signature': [rootToParent, parentToChildWrongSigner],
}
for (const [name, chain] of Object.entries(CHAINS)) {
  write(join('chains', `${name}.json`), { _comment: TEST_ONLY_HEADER, agent_id: CHILD, chain })
}

const GENERATED_AT = '2026-09-29T00:00:00.000Z'
write(join('revocations', 'none.json'), {
  _comment: TEST_ONLY_HEADER,
  generated_at: GENERATED_AT,
  revoked_delegation_ids: [],
})
write(join('revocations', 'parent-grant-revoked.json'), {
  _comment: TEST_ONLY_HEADER + ' The root principal has revoked its grant to the parent agent.',
  generated_at: GENERATED_AT,
  revoked_delegation_ids: [rootToParent.delegation_id],
})
write(join('revocations', 'malformed.json'), '@@ not json @@')
writeFileSync(join(OUT, 'revocations', 'malformed.json'), '{ "generated_at": "2026-09-29T00:00:00.000Z", "revoked_delegation_ids": [ \n')
write(join('revocations', 'stale.json'), {
  _comment: TEST_ONLY_HEADER + ' generated_at far outside any sane freshness bound.',
  generated_at: '2020-01-01T00:00:00.000Z',
  revoked_delegation_ids: [],
})

// Self-check: the valid chain must verify valid at the evaluation clock, and the
// revoked variant must come back invalid/REVOKED at index 0. A fixture set that
// fails this is not written out as usable.
const NOW = '2026-09-29T00:00:00.000Z'
const keysByVm = { [ROOT_VM]: rootKeys.publicKey, [PARENT_VM]: parentKeys.publicKey }
const options = (revoked) => ({
  now: NOW,
  trustRoot: (root) => root.issuer === ROOT && root.subject === PARENT && root.parent_delegation_id === null,
  resolveVerificationKey: (_issuer, vm) => keysByVm[vm] ?? null,
  resolveRevocation: (d) => (revoked.includes(d.delegation_id) ? 'revoked' : 'active'),
})

const checks = [
  ['valid chain, nothing revoked', CHAINS.valid, [], 'valid', undefined],
  ['valid chain, ancestor revoked', CHAINS.valid, [rootToParent.delegation_id], 'invalid', 'REVOKED'],
  ['child widens parent scope', CHAINS.widened, [], 'invalid', 'SCOPE_WIDENING'],
  ['child link expired', CHAINS.expired, [], 'invalid', 'EXPIRED'],
  ['tampered child record', CHAINS.tampered, [], 'invalid', 'ID_MISMATCH'],
  ['child signed by wrong key', CHAINS['wrong-signature'], [], 'invalid', 'SIGNATURE_INVALID'],
]

let failed = 0
for (const [label, chain, revoked, wantState, wantCode] of checks) {
  const r = verifyAuthorityDelegationChain(chain, options(revoked))
  const code = r.failures[0]?.code
  const ok = r.state === wantState && (wantCode === undefined || code === wantCode)
  if (!ok) failed++
  console.log(`${ok ? 'ok  ' : 'FAIL'}  ${label}: state=${r.state} code=${code ?? '-'} (want state=${wantState} code=${wantCode ?? '-'})`)
}
if (failed > 0) {
  console.error(`\n${failed} fixture self-check(s) failed. Fixtures written, but not usable as-is.`)
  process.exit(1)
}
console.log(`\nFixtures written to fixtures/. sandbox_id=${SANDBOX_ID} agent_id=${CHILD}`)
console.log(`root->parent delegation_id: ${rootToParent.delegation_id}`)
console.log(`parent->child delegation_id: ${parentToChild.delegation_id}`)
